In [1]:
# Load package 
import numpy as np

<h1> Exercise 1: The Simplest Consumption Model (Cake Eating Problem)

Consider the simplest consumption-saving model:

$$\begin{aligned}
    V_1^*(W) &= \max_{c_1,c_2,\dots,c_T} \{ \sqrt{c_1} +\beta \sqrt{c_2}+\beta^2\sqrt{c_3}+\cdots+\beta^T\sqrt{c_T} \} \\
    & \text{s.t.} \\
    W &= c_1 + c_2+\cdots+c_T \\
    c_t &\in \mathbb{N}, \, \forall t
\end{aligned}$$
for $T=3$, $\beta =0.9$ and $W=5$.

### 1. Solve the model using backwards induction: 

In [2]:
# 1. Setup 
beta = 0.9
W = 5
T = 3

# 2. Initialize
Vstar_bi = np.nan+np.zeros([W+1,T])
Cstar_bi = np.nan + np.zeros([W+1,T])
Cstar_bi[:,T-1] = np.arange(W+1) 
Vstar_bi[:,T-1] = np.sqrt(Cstar_bi[:,T-1])
# 3. solve

# Loop over periods
for t in range(T-2, -1, -1):  #from period T-2, until period 0, backwards  
    
    #loop over states
    for w in range(W+1):
        c = np.arange(w+1)
        
        #Fill in
        V_next = Vstar_bi[w-c,t+1] 
        
        V_guess = np.sqrt(c)+beta*V_next
        Vstar_bi[w,t] = np.amax(V_guess)
        Cstar_bi[w,t] = np.argmax(V_guess)
        
print(Cstar_bi)

[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 2.]
 [1. 2. 3.]
 [2. 2. 4.]
 [2. 3. 5.]]


### 2. Create a function with $\beta$, $W$ and $T$ as inputs. 

In [3]:
# Define a function
def solve_backwards(beta,W,T):
        # 2. Initialize
    Vstar_bi = np.nan+np.zeros([W+1,T])
    Cstar_bi = np.nan + np.zeros([W+1,T])
    Cstar_bi[:,T-1] = np.arange(W+1) 
    Vstar_bi[:,T-1] = np.sqrt(Cstar_bi[:,T-1])
    # 3. solve
    
    # Loop over periods
    for t in range(T-2, -1, -1):  #from period T-2, until period 0, backwards  
        
        #loop over states
        for w in range(W+1):
            c = np.arange(w+1)

            # Fill in
            V_next = Vstar_bi[w-c,t+1] 
        
            V_guess = np.sqrt(c)+beta*V_next
            
            Vstar_bi[w,t] = np.amax(V_guess)
            Cstar_bi[w,t] = np.argmax(V_guess)

    return Cstar_bi, Vstar_bi

### 3. Check that your function works 

Notice, C is our policy function. The policy function tells us the optimal way of spending our resources in a given period. 

In [4]:
beta = 0.9
W = 5
T = 3
C,V = solve_backwards(beta=beta, W=W, T=T)
print(C)

[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 2.]
 [1. 2. 3.]
 [2. 2. 4.]
 [2. 3. 5.]]


### 4. Use the policy function to simulate how 5 resources now can be spend optimally over 3 periods.    

In [5]:
# 4. simulate
C_backwards = np.empty(T)
W_now = W

for t in range(T):
    W_now = int(W_now)   # change the type to integreger 0,1,2,3 and so on
    # Fill in. Hint, use the solution, C, you find above
    C_now = C[W_now,t]
    C_backwards[t] = C_now 
    W_now = W_now-C_now
    

print(C_backwards)

[2. 2. 1.]


<h3> 5. Solve the model for $T = 10$.

In [6]:
# 1. Setup 
beta = 0.9
W = 5
T = 10

# 2. - 3. Solve 
C10, V10 = solve_backwards(beta,W,T)  # call function

<h3> Simulate $C_1$, $C_2$,...,$C_{10}$ using the policy function found in 5) and W=5

In [7]:
# define function
def simulate(Cstar,T,W):
    C_backwards = np.empty(T)
    W_now = W
    for t in range(T):
        W_now = int(W_now)   # change the type to integreger 0,1,2,3 and so on
        C_now = Cstar[W_now,t]
        C_backwards[t] = C_now 
        W_now = W_now-C_now
        
    return C_backwards


# 4. Simulate
C_sim = simulate(C10,T,W)  # Call function
        
print('Solution for C with T =',T,'and W =', W , ': C =',C_sim)

Solution for C with T = 10 and W = 5 : C = [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


<h3> Play around with W, $\beta$ and see the results. Are the results inline with your intuition?

In [8]:
for beta in np.linspace(0.5,0.99,5):
    print(f'\nBeta = {beta:5.1f}')
    for W in range(5,15,3):
        print(f'\n  W  = {W:3d}')
        C_now, V_now = solve_backwards(beta,W,T)
        C_sim = simulate(C_now,T,W)
        
        print(f'    V= {V_now[W,0]:4.2f}')
        print(f'    C= {C_sim}')
        
        
        
        
        


Beta =   0.5

  W  =   5
    V= 2.50
    C= [4. 1. 0. 0. 0. 0. 0. 0. 0. 0.]

  W  =   8
    V= 3.20
    C= [6. 1. 1. 0. 0. 0. 0. 0. 0. 0.]

  W  =  11
    V= 3.79
    C= [8. 2. 1. 0. 0. 0. 0. 0. 0. 0.]

  W  =  14
    V= 4.28
    C= [10.  3.  1.  0.  0.  0.  0.  0.  0.  0.]

Beta =   0.6

  W  =   5
    V= 2.74
    C= [3. 1. 1. 0. 0. 0. 0. 0. 0. 0.]

  W  =   8
    V= 3.51
    C= [4. 2. 1. 1. 0. 0. 0. 0. 0. 0.]

  W  =  11
    V= 4.16
    C= [6. 3. 1. 1. 0. 0. 0. 0. 0. 0.]

  W  =  14
    V= 4.71
    C= [9. 3. 1. 1. 0. 0. 0. 0. 0. 0.]

Beta =   0.7

  W  =   5
    V= 3.13
    C= [2. 1. 1. 1. 0. 0. 0. 0. 0. 0.]

  W  =   8
    V= 4.06
    C= [3. 2. 1. 1. 1. 0. 0. 0. 0. 0.]

  W  =  11
    V= 4.80
    C= [5. 3. 1. 1. 1. 0. 0. 0. 0. 0.]

  W  =  14
    V= 5.48
    C= [6. 3. 2. 1. 1. 1. 0. 0. 0. 0.]

Beta =   0.9

  W  =   5
    V= 3.84
    C= [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]

  W  =   8
    V= 5.17
    C= [2. 1. 1. 1. 1. 1. 1. 0. 0. 0.]

  W  =  11
    V= 6.22
    C= [2. 2. 1. 1. 1. 1. 1.